spring.application.name=CityFix
server.port=8083
server.servlet.context-path=/CityFix

spring.datasource.url=jdbc:postgresql://dpg-d6mnpg5m5p6s73fuqrc0-a/cityfixdb
spring.datasource.username=cityfixdb_user
spring.datasource.password=2p9cpY210WEMkPcdf7D67pIoOX6EN5pm

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui.html