spring.application.name=CityFix
server.port=${PORT:8083}
server.servlet.context-path=/CityFix

# ===============================
# Datasource (Local + Render)
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=${DB_DIALECT}

springdoc.swagger-ui.path=/swagger-ui.html